# SETUP

In [1]:
# import libraries

import pandas as pd
import numpy as np
from sklearn import metrics
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit
##--original
# # Import AutoGluon Libraries
# from autogluon.tabular import TabularDataset, TabularPredictor
##--modified
!pip install autogluon.tabular
from autogluon.tabular import TabularDataset, TabularPredictor

from sklearn.impute import SimpleImputer

Collecting autogluon.tabular
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular) (1.15.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular) (2.2.2)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular) (3.5)
Collecting autogluon.core==1.5.0 (from autogluon.tabular)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon.tabular)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.5.0->autogluon.tabular) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.5.0->autogluon.tabular) (2.32.3)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.5.0->autogluon.tabular) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.tabular)
  Downloading boto3-1.43.16-py3-none-any.whl.metadata (6.6 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.tabular)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (18.1.0)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (5.9.5)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (1.5.1)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (6.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<1.8.0,>=1.4.0->autogluon.tabular) (3.6.0)
Collecting botocore<1.44.0,>=1.43.16 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular)
  Downloading botocore-1.43.16-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular)
  Downloading s3transfer-0.17.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (3.2.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->autogluon.tabular) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (2025.7.14)
Downloading autogluon_tabular-1.5.0-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 24.7 MB/s eta 0:00:00
Downloading autogluon_core-1.5.0-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 34.8 MB/s eta 0:00:00
Downloading autogluon_features-1.5.0-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 kB 18.4 MB/s eta 0:00:00
Downloading autogluon_common-1.5.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 13.4 MB/s eta 0:00:00
Downloading boto3-1.43.16-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 26.0 MB/s eta 0:00:00
Downloading botocore-1.43.16-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 119.0 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.17.1-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 13.9 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3, autogluon.common, autogluon.features, autogluon.core, autogluon.tabular
Successfully installed autogluon.common-1.5.0 autogluon.core-1.5.0 autogluon.features-1.5.0 autogluon.tabular-1.5.0 boto3-1.43.16 botocore-1.43.16 jmespath-1.1.0 s3transfer-0.17.1

In [2]:
# Install AutoGluon
#!pip install autogluon.tabular

In [3]:
# load Cleveland datafile
cleveland_csv_path = "processed.cleveland.data"
cleveland_data = pd.read_csv(cleveland_csv_path, header = None)
# assign column names
##--original
# cleveland_data.set_axis(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
#                   'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
#                   'ca', 'thal', 'num'], axis = 1, inplace = True)
##--modified
cleveland_data.columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
                  'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
                  'ca', 'thal', 'num']

In [4]:
# Define label column
label = 'num'
heart_label = 'num'

# SIMPLEST OF MODELS
zero data preprocessing performed

In [5]:
cleveland_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [6]:
cleveland_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        303 non-null    object
 12  thal      303 non-null    object
 13  num       303 non-null    int64
dtypes: float64(11), int64(1), object(2)
memory usage: 33.3+ KB

## BINARY MODELING
(Note: "Cleveland" label here would need to be revised because used in Slightly Better Model below when split the data, if care.)

### PREPARE DATA

In [7]:
# make copy for binary labeling
cleveland_binary = cleveland_data.copy()
cleveland_binary['num'][cleveland_binary['num'] > 0] = 1
cleveland_binary.head()

/tmp/ipython-input-7-20290669.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  cleveland_binary['num'][cleveland_binary['num'] > 0] = 1
/tmp/ipython-input-7-20290669.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleveland_binary['num'][cleveland_binary['num'] > 0] = 1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [8]:
# split the binary data
from sklearn.model_selection import train_test_split
cleveland_train, cleveland_test = train_test_split(cleveland_binary, test_size=0.2, random_state=42)
cleveland_test_labels = cleveland_test[heart_label]
cleveland_test_nolabel = cleveland_test.drop([heart_label], axis=1)
cleveland_train_labels = cleveland_train[heart_label]
cleveland_train_nolabel = cleveland_train.drop([heart_label], axis=1)
cleveland_train.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
160,46.0,1.0,2.0,101.0,197.0,1.0,0.0,156.0,0.0,0.0,1.0,0.0,7.0,0
69,46.0,1.0,3.0,150.0,231.0,0.0,0.0,147.0,0.0,3.6,2.0,0.0,3.0,1
140,59.0,1.0,2.0,140.0,221.0,0.0,0.0,164.0,1.0,0.0,1.0,0.0,3.0,0
276,66.0,0.0,3.0,146.0,278.0,0.0,2.0,152.0,0.0,0.0,2.0,1.0,3.0,0
173,62.0,0.0,4.0,140.0,394.0,0.0,2.0,157.0,0.0,1.2,2.0,0.0,3.0,0

### MODEL - TRAIN & EVALUATE

In [9]:
# Create an instance and then fit the train data
cle_TabPre = TabularPredictor(label=heart_label, path='.').fit(cleveland_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       9.20 GB / 12.67 GB (72.6%)
Disk Space Avail:   66.64 GB / 118.86 GB (56.1%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    242
Train Data Columns: 13
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.int64(0), np.int64(1)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9387.62 MB
	Train Data (Original)  Memory Usage: 0.05 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 11 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
		('object', []) :  2 | ['ca', 'thal']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['ca', 'thal']
		('float', [])     : 8 | ['age', 'cp', 'trestbps', 'chol', 'restecg', ...]
		('int', ['bool']) : 3 | ['sex', 'fbs', 'exang']
	0.1s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 0.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 193, Val Rows: 49
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/9.2 GB
	0.7959	 = Validation score   (accuracy)
	10.36s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/9.0 GB
	0.8367	 = Validation score   (accuracy)
	0.21s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.8367	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.8776	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.8776	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.8367	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/9.0 GB
No improvement since epoch 7: early stopping
	0.8776	 = Validation score   (accuracy)
	2.88s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.8571	 = Validation score   (accuracy)
	0.8s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.9 GB
	0.8571	 = Validation score   (accuracy)
	8.71s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.8 GB
	0.8163	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.8 GB
	Ensemble Weights: {'RandomForestEntr': 1.0}
	0.8776	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 26.83s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 733.8 rows/s (49 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (49 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [10]:
# Check the performance using test data
cle_pred = cle_TabPre.predict(cleveland_test_nolabel)
cle_perf = cle_TabPre.evaluate_predictions(y_true=cleveland_test_labels, y_pred=cle_pred, auxiliary_metrics=True)

In [11]:
cle_perf2 = cle_TabPre.evaluate(data=cleveland_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [12]:
cle_perf3 = cle_TabPre.evaluate(data=cleveland_test, auxiliary_metrics=True, model='ExtraTreesGini')

In [13]:
cle_perf4 = cle_TabPre.evaluate(data=cleveland_test, auxiliary_metrics=True, model='ExtraTreesEntr')

In [14]:
#Show the leaderboard
cle_TabPre.leaderboard(cleveland_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestEntr,0.885246,0.877551,accuracy,0.084393,0.066113,0.592784,0.084393,0.066113,0.592784,1,True,4
1,ExtraTreesGini,0.885246,0.877551,accuracy,0.084867,0.076525,0.594083,0.084867,0.076525,0.594083,1,True,5
2,ExtraTreesEntr,0.885246,0.836735,accuracy,0.085177,0.076125,0.587361,0.085177,0.076125,0.587361,1,True,6
3,WeightedEnsemble_L2,0.885246,0.877551,accuracy,0.085709,0.066777,0.661602,0.001316,0.000664,0.068817,2,True,11
4,NeuralNetTorch,0.868852,0.857143,accuracy,0.010582,0.007961,8.714316,0.010582,0.007961,8.714316,1,True,9
5,RandomForestGini,0.868852,0.836735,accuracy,0.084914,0.068730,0.792554,0.084914,0.068730,0.792554,1,True,3
6,XGBoost,0.836066,0.857143,accuracy,0.011382,0.004529,0.799530,0.011382,0.004529,0.799530,1,True,8
7,LightGBMLarge,0.819672,0.816327,accuracy,0.005549,0.002175,0.371934,0.005549,0.002175,0.371934,1,True,10
8,LightGBM,0.803279,0.836735,accuracy,0.003200,0.001904,0.214755,0.003200,0.001904,0.214755,1,True,2
9,LightGBMXT,0.803279,0.795918,accuracy,0.004561,0.002565,10.363807,0.004561,0.002565,10.363807,1,True,1
10,NeuralNetFastAI,0.770492,0.877551,accuracy,0.018396,0.034192,2.879873,0.018396,0.034192,2.879873,1,True,7

In [15]:
##--original
# #Show the best model
# cle_TabPre.get_model_best()
##--modified
cle_TabPre.model_best

'WeightedEnsemble_L2'

## MULTICLASS MODELING

In [16]:
cleveland_binary.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [17]:
cleveland_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [18]:
# split the multiclass data
from sklearn.model_selection import train_test_split
mccleveland_train, mccleveland_test = train_test_split(cleveland_data, test_size=0.2, random_state=42)
mccleveland_test_labels = mccleveland_test[heart_label]
mccleveland_test_nolabel = mccleveland_test.drop([heart_label], axis=1)
mccleveland_train_labels = mccleveland_train[heart_label]
mccleveland_train_nolabel = mccleveland_train.drop([heart_label], axis=1)
mccleveland_train.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
43,59.0,1.0,3.0,150.0,212.0,1.0,0.0,157.0,0.0,1.6,1.0,0.0,3.0,0
74,44.0,1.0,4.0,110.0,197.0,0.0,2.0,177.0,0.0,0.0,1.0,1.0,3.0,1
40,65.0,0.0,4.0,150.0,225.0,0.0,2.0,114.0,0.0,1.0,2.0,3.0,7.0,4
266,52.0,1.0,4.0,128.0,204.0,1.0,0.0,156.0,1.0,1.0,2.0,0.0,?,2
87,53.0,0.0,3.0,128.0,216.0,0.0,2.0,115.0,0.0,0.0,1.0,0.0,?,0

### MODEL - TRAIN & EVALUATE

In [19]:
# Create an instance and then fit the train data
mccle_TabPre = TabularPredictor(label=heart_label, path='.').fit(mccleveland_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.76 GB / 12.67 GB (69.1%)
Disk Space Avail:   66.60 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    242
Train Data Columns: 13
Label Column:       num
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == int, but few unique label-values observed).
	5 unique label values:  [np.int64(0), np.int64(3), np.int64(1), np.int64(2), np.int64(4)]
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       multiclass
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 9 to avoid cutting too many classes.
Train Data Class Count: 5
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8970.22 MB
	Train Data (Original)  Memory Usage: 0.05 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 11 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
		('object', []) :  2 | ['ca', 'thal']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['ca', 'thal']
		('float', [])     : 8 | ['age', 'cp', 'trestbps', 'chol', 'restecg', ...]
		('int', ['bool']) : 3 | ['sex', 'fbs', 'exang']
	0.1s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 0.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.09s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 193, Val Rows: 49
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.8 GB
No improvement since epoch 3: early stopping
	0.6735	 = Validation score   (accuracy)
	1.18s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.8 GB
	0.6735	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.8 GB
	0.6327	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.6122	 = Validation score   (accuracy)
	0.81s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.6122	 = Validation score   (accuracy)
	0.82s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.6327	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.6531	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.6122	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.6735	 = Validation score   (accuracy)
	1.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.3/8.7 GB
	0.6327	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.6735	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.73s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4433.2 rows/s (49 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [20]:
# Check the performance using test data
mccle_pred = mccle_TabPre.predict(mccleveland_test_nolabel)
mccle_perf = mccle_TabPre.evaluate_predictions(y_true=mccleveland_test_labels, y_pred=mccle_pred, auxiliary_metrics=True)

In [21]:
#Show the leaderboard
mccle_TabPre.leaderboard(mccleveland_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,ExtraTreesEntr,0.524590,0.653061,accuracy,0.090528,0.076478,0.629072,0.090528,0.076478,0.629072,1,True,7
1,ExtraTreesGini,0.524590,0.632653,accuracy,0.095419,0.075870,0.640242,0.095419,0.075870,0.640242,1,True,6
2,LightGBMLarge,0.508197,0.632653,accuracy,0.010119,0.002878,0.612370,0.010119,0.002878,0.612370,1,True,10
3,RandomForestGini,0.508197,0.612245,accuracy,0.087265,0.080160,0.809198,0.087265,0.080160,0.809198,1,True,4
4,NeuralNetTorch,0.491803,0.673469,accuracy,0.011681,0.008228,1.341769,0.011681,0.008228,1.341769,1,True,9
5,LightGBM,0.491803,0.632653,accuracy,0.012449,0.005592,0.605555,0.012449,0.005592,0.605555,1,True,3
6,RandomForestEntr,0.491803,0.612245,accuracy,0.087183,0.075584,0.823998,0.087183,0.075584,0.823998,1,True,5
7,LightGBMXT,0.475410,0.673469,accuracy,0.019047,0.008233,0.620567,0.019047,0.008233,0.620567,1,True,2
8,XGBoost,0.475410,0.612245,accuracy,0.045345,0.010456,0.395395,0.045345,0.010456,0.395395,1,True,8
9,NeuralNetFastAI,0.426230,0.673469,accuracy,0.015007,0.010311,1.177208,0.015007,0.010311,1.177208,1,True,1
10,WeightedEnsemble_L2,0.426230,0.673469,accuracy,0.016840,0.011053,1.255044,0.001832,0.000742,0.077837,2,True,11

In [22]:
##--original
# #Show the best model
# mccle_TabPre.get_model_best()
##--modified
mccle_TabPre.model_best

'WeightedEnsemble_L2'

# SLIGHTLY BETTER MODEL
no missing values & stratified sampling

## DATA PREPROCESSING

### MISSING VALUES

In [23]:
# make copy of original dataframe
cleveland = cleveland_data.copy()

In [24]:
# check for missing values
cleveland.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        303 non-null    object
 12  thal      303 non-null    object
 13  num       303 non-null    int64
dtypes: float64(11), int64(1), object(2)
memory usage: 33.3+ KB

In [25]:
# replace '?' values with NaN so can impute
##--original
#cleveland['thal'].replace('?', np.NaN, inplace=True)
##--modified
cleveland['thal'].replace('?', np.nan, inplace=True)

cleveland['thal'] = cleveland['thal'].astype(float)
##--original
#cleveland['ca'].replace('?', np.NaN, inplace=True)
##--modified
cleveland['ca'].replace('?', np.nan, inplace=True)

cleveland['ca'] = cleveland['ca'].astype(float)
cleveland.tail() # to verify didn't mess up dataframe IDs

/tmp/ipython-input-25-611411134.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleveland['thal'].replace('?', np.nan, inplace=True)
/tmp/ipython-input-25-611411134.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleveland['ca'].replace('?', np.nan, inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,NaN,3.0,0

In [26]:
from sklearn.impute import SimpleImputer
# impute with mode as 'thal' and 'ca' (attributes w/ missing values) are discrete
imputeMode = SimpleImputer(strategy="most_frequent") # create mode imputer
imputeMode.fit(cleveland) # fit - learns the data
imputed = imputeMode.transform(cleveland) # transform - imputes with chosen strategy
cleveland = pd.DataFrame(imputed, columns=cleveland.columns, index=cleveland.index) # back to pandas DataFrame
cleveland.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        303 non-null    float64
 12  thal      303 non-null    float64
 13  num       303 non-null    float64
dtypes: float64(14)
memory usage: 33.3 KB

In [27]:
cleveland.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1.0
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2.0
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3.0
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1.0
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,3.0,0.0

### BINARY LABEL
(multiclass for "future research")

In [28]:
cleveland['num'][cleveland['num'] > 0] = 1
cleveland.head()

/tmp/ipython-input-28-3893717676.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  cleveland['num'][cleveland['num'] > 0] = 1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0.0

### STRATIFIED SAMPLING

(due to clear significance of sex)

In [29]:
cleveland_strat = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in cleveland_strat.split(cleveland, cleveland["num"]):
  cleveland_strat_train = cleveland.loc[train_index] # cleveland_train,
  cleveland_strat_test = cleveland.loc[test_index] # cleveland_test

In [30]:
cleveland_strat_test["num"].value_counts()/len(cleveland_strat_test)

num
0.0    0.540984
1.0    0.459016
Name: count, dtype: float64

In [31]:
cleveland_strat_train["num"].value_counts()/len(cleveland_strat_train)

num
0.0    0.541322
1.0    0.458678
Name: count, dtype: float64

Less significant for Cleveland and Statlog datasets, which have less dramatic difference in sex representation in data, but different for other three datasets.

In [32]:
# split stratified data
cleveland_strat_train_X = cleveland_strat_train.drop([heart_label], axis=1)#cleveland_train_nolabel
cleveland_strat_train_y = cleveland_strat_train[heart_label]#cleveland_train_labels
cleveland_strat_test_X = cleveland_strat_test.drop([heart_label], axis=1)#cleveland_test_nolabel
cleveland_strat_test_y = cleveland_strat_test[heart_label]#cleveland_test_labels
cleveland_strat_train_X.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
278,57.0,1.0,2.0,154.0,232.0,0.0,2.0,164.0,0.0,0.0,1.0,1.0,3.0
239,42.0,1.0,2.0,120.0,295.0,0.0,0.0,162.0,0.0,0.0,1.0,0.0,3.0
180,48.0,1.0,4.0,124.0,274.0,0.0,2.0,166.0,0.0,0.5,2.0,0.0,7.0
265,42.0,1.0,4.0,136.0,315.0,0.0,0.0,125.0,1.0,1.8,2.0,0.0,6.0
129,62.0,0.0,4.0,124.0,209.0,0.0,0.0,163.0,0.0,0.0,1.0,0.0,3.0

## BINARY MODEL

In [33]:
# Create an instance and then fit the train data
ccle_TabPre = TabularPredictor(label=heart_label, path='.').fit(cleveland_strat_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.73 GB / 12.67 GB (68.9%)
Disk Space Avail:   66.58 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    242
Train Data Columns: 13
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8934.71 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 10 | ['age', 'cp', 'trestbps', 'chol', 'restecg', ...]
		('int', ['bool']) :  3 | ['sex', 'fbs', 'exang']
	0.0s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 0.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 193, Val Rows: 49
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.9184	 = Validation score   (accuracy)
	0.29s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.898	 = Validation score   (accuracy)
	0.28s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.898	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.898	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.8776	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.898	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
No improvement since epoch 1: early stopping
	0.9388	 = Validation score   (accuracy)
	1.32s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.8776	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.9184	 = Validation score   (accuracy)
	1.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.7 GB
	0.8776	 = Validation score   (accuracy)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9388	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.72s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4284.2 rows/s (49 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (49 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [34]:
# Check the performance using test data
ccle_pred = ccle_TabPre.predict(cleveland_strat_test_X)
ccle_perf = ccle_TabPre.evaluate_predictions(y_true=cleveland_strat_test_y, y_pred=ccle_pred, auxiliary_metrics=True)

In [35]:
ccle_perf2 = ccle_TabPre.evaluate(data=cleveland_strat_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [36]:
ccle_perf3 = ccle_TabPre.evaluate(data=cleveland_strat_test, auxiliary_metrics=True, model='RandomForestGini')

In [37]:
ccle_perf4 = ccle_TabPre.evaluate(data=cleveland_strat_test, auxiliary_metrics=True, model='RandomForestEntr')

In [38]:
#Show the leaderboard
ccle_TabPre.leaderboard(cleveland_strat_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetFastAI,0.885246,0.938776,accuracy,0.015930,0.010787,1.316292,0.015930,0.010787,1.316292,1,True,7
1,WeightedEnsemble_L2,0.885246,0.938776,accuracy,0.017119,0.011437,1.409471,0.001189,0.000651,0.093180,2,True,11
2,LightGBM,0.868852,0.897959,accuracy,0.001254,0.000578,0.278262,0.001254,0.000578,0.278262,1,True,2
3,RandomForestGini,0.868852,0.897959,accuracy,0.085490,0.075969,0.607607,0.085490,0.075969,0.607607,1,True,3
4,LightGBMXT,0.852459,0.918367,accuracy,0.004583,0.000967,0.293906,0.004583,0.000967,0.293906,1,True,1
5,RandomForestEntr,0.852459,0.897959,accuracy,0.083206,0.065492,0.605338,0.083206,0.065492,0.605338,1,True,4
6,ExtraTreesGini,0.836066,0.877551,accuracy,0.085675,0.074968,0.587162,0.085675,0.074968,0.587162,1,True,5
7,ExtraTreesEntr,0.819672,0.897959,accuracy,0.087178,0.066484,0.663361,0.087178,0.066484,0.663361,1,True,6
8,LightGBMLarge,0.803279,0.877551,accuracy,0.001235,0.000607,0.333681,0.001235,0.000607,0.333681,1,True,10
9,NeuralNetTorch,0.803279,0.918367,accuracy,0.009170,0.006778,1.013694,0.009170,0.006778,1.013694,1,True,9
10,XGBoost,0.786885,0.877551,accuracy,0.009311,0.003084,0.159274,0.009311,0.003084,0.159274,1,True,8

In [39]:
#Show the leaderboard
ccle_TabPre.leaderboard( silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetFastAI,0.938776,accuracy,0.010787,1.316292,0.010787,1.316292,1,True,7
1,WeightedEnsemble_L2,0.938776,accuracy,0.011437,1.409471,0.000651,0.093180,2,True,11
2,LightGBMXT,0.918367,accuracy,0.000967,0.293906,0.000967,0.293906,1,True,1
3,NeuralNetTorch,0.918367,accuracy,0.006778,1.013694,0.006778,1.013694,1,True,9
4,LightGBM,0.897959,accuracy,0.000578,0.278262,0.000578,0.278262,1,True,2
5,RandomForestEntr,0.897959,accuracy,0.065492,0.605338,0.065492,0.605338,1,True,4
6,ExtraTreesEntr,0.897959,accuracy,0.066484,0.663361,0.066484,0.663361,1,True,6
7,RandomForestGini,0.897959,accuracy,0.075969,0.607607,0.075969,0.607607,1,True,3
8,LightGBMLarge,0.877551,accuracy,0.000607,0.333681,0.000607,0.333681,1,True,10
9,XGBoost,0.877551,accuracy,0.003084,0.159274,0.003084,0.159274,1,True,8
10,ExtraTreesGini,0.877551,accuracy,0.074968,0.587162,0.074968,0.587162,1,True,5

In [40]:
##--original
# #Show the best model
# cle_TabPre.get_model_best()
##--modified
cle_TabPre.model_best

'WeightedEnsemble_L2'

# MODEL USING ONLY CORRELATED ATTRIBUTES
(incl. no missing values & stratified sampling)

## DATA PREPROCESSING

### REMOVE UNCORRELATED ATTRIBUTES

In [41]:
# check correlation
cleveland_correlation = cleveland.corr()
cleveland_correlation['num'].sort_values()

thalach    -0.417167
fbs         0.025264
chol        0.085164
trestbps    0.150825
restecg     0.169202
age         0.223120
sex         0.276816
slope       0.339213
cp          0.414446
oldpeak     0.424510
exang       0.431894
ca          0.460033
thal        0.522057
num         1.000000
Name: num, dtype: float64

In [42]:
# eliminate columns with correlation less than abs(0.2)
drop_columns = ['fbs', 'chol', 'trestbps', 'restecg']
cleveland_downsized = cleveland.drop(columns = drop_columns)
cleveland_downsized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age      303 non-null    float64
 1   sex      303 non-null    float64
 2   cp       303 non-null    float64
 3   thalach  303 non-null    float64
 4   exang    303 non-null    float64
 5   oldpeak  303 non-null    float64
 6   slope    303 non-null    float64
 7   ca       303 non-null    float64
 8   thal     303 non-null    float64
 9   num      303 non-null    float64
dtypes: float64(10)
memory usage: 23.8 KB

### STRATIFIED SPLIT OF DATA

In [43]:
cleveland_downsized_strat = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in cleveland_downsized_strat.split(cleveland_downsized, cleveland_downsized["num"]):
  cleveland_downsized_strat_train = cleveland_downsized.loc[train_index]
  cleveland_downsized_strat_test = cleveland_downsized.loc[test_index]

In [44]:
cleveland_downsized_strat_test["num"].value_counts()/len(cleveland_downsized_strat_test)

num
0.0    0.540984
1.0    0.459016
Name: count, dtype: float64

In [45]:
cleveland_downsized_strat_train["num"].value_counts()/len(cleveland_downsized_strat_train)

num
0.0    0.541322
1.0    0.458678
Name: count, dtype: float64

In [46]:
# split stratified data
cleveland_downsized_strat_train_X = cleveland_downsized_strat_train.drop([heart_label], axis=1)
cleveland_downsized_strat_train_y = cleveland_downsized_strat_train[heart_label]
cleveland_downsized_strat_test_X = cleveland_downsized_strat_test.drop([heart_label], axis=1)
cleveland_downsized_strat_test_y = cleveland_downsized_strat_test[heart_label]
cleveland_downsized_strat_train_X.sample(5)

      age  sex   cp  thalach  exang  oldpeak  slope   ca  thal
83   68.0  1.0  3.0    150.0    1.0      1.6    2.0  0.0   7.0
96   59.0  1.0  4.0    142.0    1.0      1.2    2.0  1.0   7.0
289  56.0  1.0  2.0    169.0    0.0      0.0    3.0  0.0   3.0
15   57.0  1.0  3.0    174.0    0.0      1.6    1.0  0.0   3.0
158  60.0  1.0  4.0    170.0    0.0      1.2    2.0  2.0   7.0

## BINARY MODELING

In [47]:
# Create an instance and then fit the train data
cccle_TabPre = TabularPredictor(label=heart_label, path='.').fit(cleveland_downsized_strat_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.72 GB / 12.67 GB (68.8%)
Disk Space Avail:   66.60 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    242
Train Data Columns: 9
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8933.22 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 2 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 9 | ['age', 'sex', 'cp', 'thalach', 'exang', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 7 | ['age', 'cp', 'thalach', 'oldpeak', 'slope', ...]
		('int', ['bool']) : 2 | ['sex', 'exang']
	0.0s = Fit runtime
	9 features in original data used to generate 9 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 193, Val Rows: 49
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.9184	 = Validation score   (accuracy)
	0.29s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.898	 = Validation score   (accuracy)
	0.25s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.898	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.898	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.8571	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.8571	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
No improvement since epoch 8: early stopping
	0.9184	 = Validation score   (accuracy)
	1.29s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.898	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.9184	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.7 GB
	0.898	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.9184	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.3s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 29841.9 rows/s (49 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (49 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [48]:
# Check the performance using test data
cccle_pred = cccle_TabPre.predict(cleveland_downsized_strat_test_X)
cccle_perf = cccle_TabPre.evaluate_predictions(y_true=cleveland_downsized_strat_test_y, y_pred=cccle_pred, auxiliary_metrics=True)

In [49]:
cccle_perf2 = cccle_TabPre.evaluate(data=cleveland_downsized_strat_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [50]:
cccle_perf3 = cccle_TabPre.evaluate(data=cleveland_downsized_strat_test, auxiliary_metrics=True, model='RandomForestGini')

In [51]:
cccle_perf4 = cccle_TabPre.evaluate(data=cleveland_downsized_strat_test, auxiliary_metrics=True, model='RandomForestEntr')

In [52]:
#Show the leaderboard
cccle_TabPre.leaderboard(cleveland_downsized_strat_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMXT,0.868852,0.918367,accuracy,0.005529,0.000920,0.286866,0.005529,0.000920,0.286866,1,True,1
1,WeightedEnsemble_L2,0.868852,0.918367,accuracy,0.007607,0.001642,0.354324,0.002077,0.000722,0.067458,2,True,11
2,ExtraTreesEntr,0.868852,0.857143,accuracy,0.067344,0.075750,0.633875,0.067344,0.075750,0.633875,1,True,6
3,LightGBM,0.852459,0.897959,accuracy,0.001663,0.000463,0.251066,0.001663,0.000463,0.251066,1,True,2
4,ExtraTreesGini,0.852459,0.857143,accuracy,0.066850,0.076101,0.623557,0.066850,0.076101,0.623557,1,True,5
5,RandomForestGini,0.852459,0.897959,accuracy,0.077373,0.076119,0.605698,0.077373,0.076119,0.605698,1,True,3
6,LightGBMLarge,0.836066,0.897959,accuracy,0.007564,0.000942,0.397824,0.007564,0.000942,0.397824,1,True,10
7,NeuralNetTorch,0.836066,0.918367,accuracy,0.012288,0.006857,0.630054,0.012288,0.006857,0.630054,1,True,9
8,RandomForestEntr,0.836066,0.897959,accuracy,0.067825,0.077371,0.601122,0.067825,0.077371,0.601122,1,True,4
9,XGBoost,0.786885,0.897959,accuracy,0.013236,0.001952,0.116888,0.013236,0.001952,0.116888,1,True,8
10,NeuralNetFastAI,0.786885,0.918367,accuracy,0.017563,0.009519,1.292771,0.017563,0.009519,1.292771,1,True,7

In [53]:
cccle_TabPre.leaderboard(silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMXT,0.918367,accuracy,0.000920,0.286866,0.000920,0.286866,1,True,1
1,WeightedEnsemble_L2,0.918367,accuracy,0.001642,0.354324,0.000722,0.067458,2,True,11
2,NeuralNetTorch,0.918367,accuracy,0.006857,0.630054,0.006857,0.630054,1,True,9
3,NeuralNetFastAI,0.918367,accuracy,0.009519,1.292771,0.009519,1.292771,1,True,7
4,LightGBM,0.897959,accuracy,0.000463,0.251066,0.000463,0.251066,1,True,2
5,LightGBMLarge,0.897959,accuracy,0.000942,0.397824,0.000942,0.397824,1,True,10
6,XGBoost,0.897959,accuracy,0.001952,0.116888,0.001952,0.116888,1,True,8
7,RandomForestGini,0.897959,accuracy,0.076119,0.605698,0.076119,0.605698,1,True,3
8,RandomForestEntr,0.897959,accuracy,0.077371,0.601122,0.077371,0.601122,1,True,4
9,ExtraTreesEntr,0.857143,accuracy,0.075750,0.633875,0.075750,0.633875,1,True,6
10,ExtraTreesGini,0.857143,accuracy,0.076101,0.623557,0.076101,0.623557,1,True,5

In [54]:
##--original
# #Show the best model
# cccle_TabPre.get_model_best()
##--modified
cccle_TabPre.model_best

'WeightedEnsemble_L2'

# Hungarian dataset

In [55]:
# load Hungarian datafile
hungarian_csv_path = "reprocessed.hungarian.data"
hungarian_data = pd.read_csv(hungarian_csv_path, delimiter = ' ', header = None)
# assign column names
##--original
# hungarian_data.set_axis(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
#                   'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
#                   'ca', 'thal', 'num'], axis = 1, inplace = True)
##--modified
hungarian_data.columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
                  'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
                  'ca', 'thal', 'num']

In [56]:
# Define label column
label = 'num'
heart_label = 'num'

# SIMPLEST OF MODELS
zero data preprocessing performed

In [57]:
hungarian_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40.0,1.0,2.0,140.0,289.0,0.0,0.0,172.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
1,49.0,0.0,3.0,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,-9.0,-9.0,1.0
2,37.0,1.0,2.0,130.0,283.0,0.0,1.0,98.0,0.0,0.0,-9.0,-9.0,-9.0,0.0
3,48.0,0.0,4.0,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,-9.0,-9.0,3.0
4,54.0,1.0,3.0,150.0,-9.0,0.0,0.0,122.0,0.0,0.0,-9.0,-9.0,-9.0,0.0

In [58]:
hungarian_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       294 non-null    float64
 1   sex       294 non-null    float64
 2   cp        294 non-null    float64
 3   trestbps  294 non-null    float64
 4   chol      294 non-null    float64
 5   fbs       294 non-null    float64
 6   restecg   294 non-null    float64
 7   thalach   294 non-null    float64
 8   exang     294 non-null    float64
 9   oldpeak   294 non-null    float64
 10  slope     294 non-null    float64
 11  ca        294 non-null    float64
 12  thal      294 non-null    float64
 13  num       294 non-null    float64
dtypes: float64(14)
memory usage: 32.4 KB

## BINARY MODELING
(Note: "Cleveland" label here would need to be revised because used in Slightly Better Model below when split the data, if care.)

### PREPARE DATA

In [59]:
# make copy of original dataframe
hungarian_basic = hungarian_data.copy()
# convert unknowns (-9.0) to NaN
##--original
#hungarian_basic.replace(-9.0, np.NaN, inplace=True)
##--modified
hungarian_basic.replace(-9.0, np.nan, inplace=True)

# make copy for binary labeling
hungarian_basic['num'][hungarian_basic['num'] > 0] = 1
hungarian_basic.head()

/tmp/ipython-input-59-1188696166.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  hungarian_basic['num'][hungarian_basic['num'] > 0] = 1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40.0,1.0,2.0,140.0,289.0,0.0,0.0,172.0,0.0,0.0,NaN,NaN,NaN,0.0
1,49.0,0.0,3.0,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,NaN,NaN,1.0
2,37.0,1.0,2.0,130.0,283.0,0.0,1.0,98.0,0.0,0.0,NaN,NaN,NaN,0.0
3,48.0,0.0,4.0,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,NaN,NaN,1.0
4,54.0,1.0,3.0,150.0,NaN,0.0,0.0,122.0,0.0,0.0,NaN,NaN,NaN,0.0

In [60]:
# try dropping slope, ca, and thal
hungarian_basic.drop(['slope', 'ca', 'thal', ], axis=1, inplace=True) # did not fix error

In [61]:
# split the binary data
from sklearn.model_selection import train_test_split
hungarian_basic_train, hungarian_basic_test = train_test_split(hungarian_basic, test_size=0.2, random_state=42)
hungarian_basic_test_labels = hungarian_basic_test[heart_label]
hungarian_basic_test_nolabel = hungarian_basic_test.drop([heart_label], axis=1)
hungarian_basic_train_labels = hungarian_basic_train[heart_label]
hungarian_basic_train_nolabel = hungarian_basic_train.drop([heart_label], axis=1)
hungarian_basic_train.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
85,66.0,1.0,4.0,140.0,NaN,0.0,0.0,94.0,1.0,1.0,1.0
217,39.0,1.0,4.0,110.0,280.0,0.0,0.0,150.0,0.0,0.0,1.0
171,29.0,1.0,2.0,120.0,243.0,0.0,0.0,160.0,0.0,0.0,0.0
104,46.0,1.0,4.0,118.0,186.0,0.0,0.0,124.0,0.0,0.0,1.0
174,49.0,1.0,3.0,140.0,187.0,0.0,0.0,172.0,0.0,0.0,0.0

### MODEL - TRAIN & EVALUATE

In [62]:
#hungarian_basic_train.to_csv('hungarian.csv')

In [63]:
#print(hungarian_basic_train.loc[[294]])

In [64]:
hungarian_basic_train = hungarian_basic_train.drop([294])

In [65]:
# Create an instance and then fit the train data
hun_TabPre = TabularPredictor(label=heart_label, path='.').fit(hungarian_basic_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.73 GB / 12.67 GB (68.9%)
Disk Space Avail:   66.59 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    235
Train Data Columns: 10
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8923.56 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 10 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 9 | ['age', 'cp', 'trestbps', 'chol', 'fbs', ...]
		('int', ['bool']) : 1 | ['sex']
	0.0s = Fit runtime
	10 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 0.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 188, Val Rows: 47
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8511	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8723	 = Validation score   (accuracy)
	0.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.8511	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.8511	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.8723	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.8511	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
No improvement since epoch 8: early stopping
	0.8936	 = Validation score   (accuracy)
	1.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.8723	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8723	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.7 GB
	0.8723	 = Validation score   (accuracy)
	0.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.8936	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.25s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4139.8 rows/s (47 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (47 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [66]:
# Check the performance using test data
hun_pred = hun_TabPre.predict(hungarian_basic_test_nolabel)
hun_perf = hun_TabPre.evaluate_predictions(y_true=hungarian_basic_test_labels, y_pred=hun_pred, auxiliary_metrics=True)

In [67]:
#Show the leaderboard
hun_TabPre.leaderboard(hungarian_basic_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetTorch,0.813559,0.872340,accuracy,0.008876,0.007166,0.490116,0.008876,0.007166,0.490116,1,True,9
1,XGBoost,0.796610,0.872340,accuracy,0.009167,0.001989,0.106143,0.009167,0.001989,0.106143,1,True,8
2,RandomForestEntr,0.796610,0.851064,accuracy,0.083967,0.076720,0.612049,0.083967,0.076720,0.612049,1,True,4
3,RandomForestGini,0.796610,0.851064,accuracy,0.086553,0.065676,0.624561,0.086553,0.065676,0.624561,1,True,3
4,LightGBM,0.779661,0.872340,accuracy,0.003637,0.000909,0.390320,0.003637,0.000909,0.390320,1,True,2
5,LightGBMLarge,0.779661,0.872340,accuracy,0.003695,0.001167,0.392916,0.003695,0.001167,0.392916,1,True,10
6,ExtraTreesEntr,0.779661,0.851064,accuracy,0.084277,0.077547,0.616479,0.084277,0.077547,0.616479,1,True,6
7,ExtraTreesGini,0.779661,0.872340,accuracy,0.084414,0.077328,0.618551,0.084414,0.077328,0.618551,1,True,5
8,LightGBMXT,0.762712,0.851064,accuracy,0.001860,0.000872,0.399504,0.001860,0.000872,0.399504,1,True,1
9,NeuralNetFastAI,0.762712,0.893617,accuracy,0.013431,0.010407,1.155352,0.013431,0.010407,1.155352,1,True,7
10,WeightedEnsemble_L2,0.762712,0.893617,accuracy,0.014699,0.011353,1.226354,0.001268,0.000946,0.071002,2,True,11

In [68]:
##--original
# #Show the best model
# hun_TabPre.get_model_best()
##--modified
hun_TabPre.model_best

'WeightedEnsemble_L2'

## SLIGHTLY BETTER MODEL
no missing values & stratified sampling

### DATA PREPROCESSING

#### MISSING VALUES

In [69]:
# make copy of original dataframe
hungarian = hungarian_data.copy()

In [70]:
# convert unknowns (-9.0) to NaN
##--original
#hungarian.replace(-9.0, np.NaN, inplace=True)
##--modified
hungarian.replace(-9.0, np.nan, inplace=True)

In [71]:
# check for missing values
hungarian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       294 non-null    float64
 1   sex       294 non-null    float64
 2   cp        294 non-null    float64
 3   trestbps  293 non-null    float64
 4   chol      271 non-null    float64
 5   fbs       286 non-null    float64
 6   restecg   293 non-null    float64
 7   thalach   293 non-null    float64
 8   exang     293 non-null    float64
 9   oldpeak   294 non-null    float64
 10  slope     104 non-null    float64
 11  ca        4 non-null      float64
 12  thal      28 non-null     float64
 13  num       294 non-null    float64
dtypes: float64(14)
memory usage: 32.4 KB

In [72]:
print(hungarian.loc[[294]])

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
294  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN

     slope  ca  thal  num
294    NaN NaN   NaN  NaN

In [73]:
hungarian = hungarian.drop([294])

In [74]:
# drop slope, ca, and thal due to >50% of values missing
hungarian.drop(['slope', 'ca', 'thal'], axis=1, inplace=True)

In [75]:
hungarian.tail() # check if next code block is needed

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
289,48.0,0.0,2.0,NaN,308.0,0.0,1.0,NaN,NaN,2.0,0.0
290,36.0,1.0,2.0,120.0,166.0,0.0,0.0,180.0,0.0,0.0,0.0
291,48.0,1.0,3.0,110.0,211.0,0.0,0.0,138.0,0.0,0.0,0.0
292,47.0,0.0,2.0,140.0,257.0,0.0,0.0,135.0,0.0,1.0,0.0
293,53.0,1.0,4.0,130.0,182.0,0.0,0.0,148.0,0.0,0.0,0.0

In [76]:
from sklearn.impute import SimpleImputer
# impute discrete values using mode ()
imputeMode = SimpleImputer(strategy="most_frequent") # create mode imputer
hungarian_disc = pd.concat([hungarian.pop(x) for x in ['fbs', 'restecg', 'exang']], axis=1) # isolate discrete
imputeMode.fit(hungarian_disc) # fit - learns the data
imputed_disc = imputeMode.transform(hungarian_disc) # transform - imputes with chosen strategy
hungarian_disc_imp = pd.DataFrame(imputed_disc, columns=hungarian_disc.columns, index=hungarian.index) # back to pandas DataFrame
hungarian_disc_imp.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   fbs      294 non-null    float64
 1   restecg  294 non-null    float64
 2   exang    294 non-null    float64
dtypes: float64(3)
memory usage: 7.0 KB

In [77]:
# NEED TO COMBINE cat, cont, and remaining
from sklearn.impute import SimpleImputer
# impute continuous values using mean
imputeMean = SimpleImputer(strategy="mean") # create mode imputer
hungarian_cont = pd.concat([hungarian.pop(x) for x in ['trestbps', 'chol', 'thalach']], axis=1) # isolate continuous
imputeMean.fit(hungarian_cont) # fit - learns the data
imputed_cont = imputeMean.transform(hungarian_cont) # transform - imputes with chosen strategy
hungarian_cont_imp = pd.DataFrame(imputed_cont, columns=hungarian_cont.columns, index=hungarian.index) # back to pandas DataFrame
hungarian_cont_imp.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   trestbps  294 non-null    float64
 1   chol      294 non-null    float64
 2   thalach   294 non-null    float64
dtypes: float64(3)
memory usage: 7.0 KB

In [78]:
hungarian_imp = pd.concat((hungarian_cont_imp, hungarian_disc_imp, hungarian), axis=1)

In [79]:
hungarian_imp.head() # check for anything obviously wonky

,trestbps,chol,thalach,fbs,restecg,exang,age,sex,cp,oldpeak,num
0,140.0,289.000000,172.0,0.0,0.0,0.0,40.0,1.0,2.0,0.0,0.0
1,160.0,180.000000,156.0,0.0,0.0,0.0,49.0,0.0,3.0,1.0,1.0
2,130.0,283.000000,98.0,0.0,1.0,0.0,37.0,1.0,2.0,0.0,0.0
3,138.0,214.000000,108.0,0.0,0.0,1.0,48.0,0.0,4.0,1.5,3.0
4,150.0,250.848708,122.0,0.0,0.0,0.0,54.0,1.0,3.0,0.0,0.0

In [80]:
hungarian_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   trestbps  294 non-null    float64
 1   chol      294 non-null    float64
 2   thalach   294 non-null    float64
 3   fbs       294 non-null    float64
 4   restecg   294 non-null    float64
 5   exang     294 non-null    float64
 6   age       294 non-null    float64
 7   sex       294 non-null    float64
 8   cp        294 non-null    float64
 9   oldpeak   294 non-null    float64
 10  num       294 non-null    float64
dtypes: float64(11)
memory usage: 25.4 KB

#### BINARY LABEL
(multiclass for "future research")

In [81]:
hungarian_imp['num'][hungarian_imp['num'] > 0] = 1
hungarian_imp.head()

/tmp/ipython-input-81-1424882858.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  hungarian_imp['num'][hungarian_imp['num'] > 0] = 1

,trestbps,chol,thalach,fbs,restecg,exang,age,sex,cp,oldpeak,num
0,140.0,289.000000,172.0,0.0,0.0,0.0,40.0,1.0,2.0,0.0,0.0
1,160.0,180.000000,156.0,0.0,0.0,0.0,49.0,0.0,3.0,1.0,1.0
2,130.0,283.000000,98.0,0.0,1.0,0.0,37.0,1.0,2.0,0.0,0.0
3,138.0,214.000000,108.0,0.0,0.0,1.0,48.0,0.0,4.0,1.5,1.0
4,150.0,250.848708,122.0,0.0,0.0,0.0,54.0,1.0,3.0,0.0,0.0

#### STRATIFIED SAMPLING
(due to difference in sex representation)

In [82]:
hungarian_imp_strat = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in hungarian_imp_strat.split(hungarian_imp, hungarian_imp["num"]):
  hungarian_imp_strat_train = hungarian_imp.loc[train_index]
  hungarian_imp_strat_test = hungarian_imp.loc[test_index]

In [83]:
hungarian_imp_strat_test["num"].value_counts()/len(hungarian_imp_strat_test)

num
0.0    0.644068
1.0    0.355932
Name: count, dtype: float64

In [84]:
hungarian_imp_strat_train["num"].value_counts()/len(hungarian_imp_strat_train)

num
0.0    0.638298
1.0    0.361702
Name: count, dtype: float64

Less significant for Cleveland and Statlog datasets, which have less dramatic difference in sex representation in data, but different for other three datasets.

In [85]:
# split stratified data
hungarian_imp_strat_train_X = hungarian_imp_strat_train.drop([heart_label], axis=1)
hungarian_imp_strat_train_y = hungarian_imp_strat_train[heart_label]
hungarian_imp_strat_test_X = hungarian_imp_strat_test.drop([heart_label], axis=1)
hungarian_imp_strat_test_y = hungarian_imp_strat_test[heart_label]
hungarian_imp_strat_train_X.sample(5)

     trestbps   chol  thalach  fbs  restecg  exang   age  sex   cp  oldpeak
206     150.0  215.0    140.0  0.0      0.0    1.0  50.0  1.0  4.0      0.0
93      160.0  329.0     92.0  0.0      0.0    1.0  48.0  1.0  4.0      1.5
125     120.0  246.0    110.0  0.0      0.0    0.0  54.0  1.0  2.0      0.0
62      140.0  224.0    144.0  0.0      0.0    0.0  45.0  1.0  4.0      0.0
201     110.0  249.0    150.0  0.0      0.0    0.0  47.0  1.0  1.0      0.0

### BINARY MODEL

In [86]:
# Create an instance and then fit the train data
hhun_TabPre = TabularPredictor(label=heart_label, path='.').fit(hungarian_imp_strat_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.73 GB / 12.67 GB (68.9%)
Disk Space Avail:   66.60 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    235
Train Data Columns: 10
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8934.48 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 10 | ['trestbps', 'chol', 'thalach', 'fbs', 'restecg', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 7 | ['trestbps', 'chol', 'thalach', 'restecg', 'age', ...]
		('int', ['bool']) : 3 | ['fbs', 'exang', 'sex']
	0.0s = Fit runtime
	10 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 188, Val Rows: 47
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8936	 = Validation score   (accuracy)
	0.27s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8723	 = Validation score   (accuracy)
	0.26s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.8298	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.8511	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.8298	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.8511	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.9362	 = Validation score   (accuracy)
	1.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.8723	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8936	 = Validation score   (accuracy)
	0.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.7 GB
	0.8511	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9362	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.89s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4347.7 rows/s (47 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (47 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [87]:
hhun_pred = hhun_TabPre.predict(hungarian_imp_strat_test_X)
hhun_perf = hhun_TabPre.evaluate_predictions(y_true=hungarian_imp_strat_test_y, y_pred=hhun_pred, auxiliary_metrics=True)

In [88]:
hhun_perf2 =  hhun_TabPre.evaluate(data=hungarian_imp_strat_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [89]:
hhun_perf3 =  hhun_TabPre.evaluate(data=hungarian_imp_strat_test, auxiliary_metrics=True, model='ExtraTreesEntr')

In [90]:
hhun_perf4 =  hhun_TabPre.evaluate(data=hungarian_imp_strat_test, auxiliary_metrics=True, model='RandomForestEntr')

In [91]:
#Show the leaderboard
hhun_TabPre.leaderboard(hungarian_imp_strat_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBM,0.881356,0.872340,accuracy,0.001113,0.000606,0.257082,0.001113,0.000606,0.257082,1,True,2
1,XGBoost,0.881356,0.872340,accuracy,0.009041,0.002005,0.107808,0.009041,0.002005,0.107808,1,True,8
2,LightGBMXT,0.847458,0.893617,accuracy,0.002083,0.000524,0.266905,0.002083,0.000524,0.266905,1,True,1
3,RandomForestGini,0.847458,0.829787,accuracy,0.075114,0.075229,0.606789,0.075114,0.075229,0.606789,1,True,3
4,RandomForestEntr,0.847458,0.851064,accuracy,0.084247,0.064798,0.618649,0.084247,0.064798,0.618649,1,True,4
5,ExtraTreesEntr,0.830508,0.851064,accuracy,0.083924,0.054222,0.717335,0.083924,0.054222,0.717335,1,True,6
6,NeuralNetTorch,0.813559,0.893617,accuracy,0.010039,0.006733,0.666987,0.010039,0.006733,0.666987,1,True,9
7,LightGBMLarge,0.813559,0.851064,accuracy,0.018437,0.002429,0.466118,0.018437,0.002429,0.466118,1,True,10
8,ExtraTreesGini,0.813559,0.829787,accuracy,0.084890,0.054175,0.722687,0.084890,0.054175,0.722687,1,True,5
9,NeuralNetFastAI,0.745763,0.936170,accuracy,0.015338,0.010098,1.586052,0.015338,0.010098,1.586052,1,True,7
10,WeightedEnsemble_L2,0.745763,0.936170,accuracy,0.017121,0.010810,1.658726,0.001782,0.000713,0.072675,2,True,11

In [92]:
hhun_TabPre.leaderboard(silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetFastAI,0.936170,accuracy,0.010098,1.586052,0.010098,1.586052,1,True,7
1,WeightedEnsemble_L2,0.936170,accuracy,0.010810,1.658726,0.000713,0.072675,2,True,11
2,LightGBMXT,0.893617,accuracy,0.000524,0.266905,0.000524,0.266905,1,True,1
3,NeuralNetTorch,0.893617,accuracy,0.006733,0.666987,0.006733,0.666987,1,True,9
4,LightGBM,0.872340,accuracy,0.000606,0.257082,0.000606,0.257082,1,True,2
5,XGBoost,0.872340,accuracy,0.002005,0.107808,0.002005,0.107808,1,True,8
6,LightGBMLarge,0.851064,accuracy,0.002429,0.466118,0.002429,0.466118,1,True,10
7,ExtraTreesEntr,0.851064,accuracy,0.054222,0.717335,0.054222,0.717335,1,True,6
8,RandomForestEntr,0.851064,accuracy,0.064798,0.618649,0.064798,0.618649,1,True,4
9,ExtraTreesGini,0.829787,accuracy,0.054175,0.722687,0.054175,0.722687,1,True,5
10,RandomForestGini,0.829787,accuracy,0.075229,0.606789,0.075229,0.606789,1,True,3

In [93]:
##--original
# #Show the best model
# hhun_TabPre.get_model_best()
##--modified
hhun_TabPre.model_best

'WeightedEnsemble_L2'

## REDUCED FOR CORRELATION
(incl. no missing values & stratified sampling)

### DATA PREPROCESSING

#### REMOVE UNCORRELATED ATTRIBUTES

In [94]:
# check correlation
hungarian_imp_correlation = hungarian_imp.corr()
hungarian_imp_correlation['num'].sort_values()

thalach    -0.331074
restecg    -0.031988
trestbps    0.139582
age         0.159315
fbs         0.162869
chol        0.202372
sex         0.272781
cp          0.505864
oldpeak     0.545700
exang       0.584541
num         1.000000
Name: num, dtype: float64

In [95]:
# eliminate columns with correlation less than abs(0.2)
drop_columns = ['age', 'fbs', 'trestbps', 'restecg']
hungarian_imp_downsized = hungarian_imp.drop(columns = drop_columns)
hungarian_imp_downsized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   chol     294 non-null    float64
 1   thalach  294 non-null    float64
 2   exang    294 non-null    float64
 3   sex      294 non-null    float64
 4   cp       294 non-null    float64
 5   oldpeak  294 non-null    float64
 6   num      294 non-null    float64
dtypes: float64(7)
memory usage: 16.2 KB

#### STRATIFIED SPLIT OF DATA

In [96]:
hungarian_imp_downsized_strat = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in hungarian_imp_downsized_strat.split(hungarian_imp_downsized, hungarian_imp_downsized["num"]):
  hungarian_imp_downsized_strat_train = hungarian_imp_downsized.loc[train_index]
  hungarian_imp_downsized_strat_test = hungarian_imp_downsized.loc[test_index]

In [97]:
hungarian_imp_downsized_strat_test["num"].value_counts()/len(hungarian_imp_downsized_strat_test)

num
0.0    0.644068
1.0    0.355932
Name: count, dtype: float64

In [98]:
# split stratified data
hungarian_imp_downsized_strat_train_X = hungarian_imp_downsized_strat_train.drop([heart_label], axis=1)
hungarian_imp_downsized_strat_train_y = hungarian_imp_downsized_strat_train[heart_label]
hungarian_imp_downsized_strat_test_X = hungarian_imp_downsized_strat_test.drop([heart_label], axis=1)
hungarian_imp_downsized_strat_test_y = hungarian_imp_downsized_strat_test[heart_label]
hungarian_imp_downsized_strat_train_X.sample(5)

      chol  thalach  exang  sex   cp  oldpeak
67   225.0    184.0    0.0  1.0  2.0      0.0
267  298.0    110.0    1.0  1.0  4.0      1.0
284  344.0    160.0    0.0  0.0  2.0      0.0
74   268.0    128.0    1.0  1.0  4.0      1.5
260  320.0    155.0    0.0  0.0  2.0      0.0

### BINARY MODELING

In [99]:
# Create an instance and then fit the train data
hhhun_TabPre = TabularPredictor(label=heart_label, path='.').fit(hungarian_imp_downsized_strat_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.73 GB / 12.67 GB (68.9%)
Disk Space Avail:   66.59 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    235
Train Data Columns: 6
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8935.26 MB
	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 2 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 6 | ['chol', 'thalach', 'exang', 'sex', 'cp', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 4 | ['chol', 'thalach', 'cp', 'oldpeak']
		('int', ['bool']) : 2 | ['exang', 'sex']
	0.0s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 188, Val Rows: 47
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8936	 = Validation score   (accuracy)
	0.27s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8936	 = Validation score   (accuracy)
	0.26s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.8511	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.8723	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.8723	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.8723	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
No improvement since epoch 0: early stopping
	0.9149	 = Validation score   (accuracy)
	0.81s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.9149	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8936	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.7 GB
	0.8723	 = Validation score   (accuracy)
	0.34s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.7 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9149	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.73s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4687.2 rows/s (47 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (47 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [100]:
hhhun_pred = hhhun_TabPre.predict(hungarian_imp_downsized_strat_test_X)
hhhun_perf = hhhun_TabPre.evaluate_predictions(y_true=hungarian_imp_downsized_strat_test_y, y_pred=hhhun_pred, auxiliary_metrics=True)

In [101]:
hhhun_perf2 =  hhhun_TabPre.evaluate(data=hungarian_imp_downsized_strat_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [102]:
hhhun_perf2 =  hhhun_TabPre.evaluate(data=hungarian_imp_downsized_strat_test, auxiliary_metrics=True, model='RandomForestEntr')

In [103]:
hhhun_perf2 =  hhhun_TabPre.evaluate(data=hungarian_imp_downsized_strat_test, auxiliary_metrics=True, model='ExtraTreesGini')

In [104]:
#Show the leaderboard
hhhun_TabPre.leaderboard(hungarian_imp_downsized_strat_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestEntr,0.898305,0.872340,accuracy,0.066779,0.066584,0.610194,0.066779,0.066584,0.610194,1,True,4
1,RandomForestGini,0.898305,0.851064,accuracy,0.068984,0.076370,0.604541,0.068984,0.076370,0.604541,1,True,3
2,LightGBM,0.881356,0.893617,accuracy,0.001447,0.000488,0.259475,0.001447,0.000488,0.259475,1,True,2
3,XGBoost,0.864407,0.914894,accuracy,0.013530,0.002117,0.102391,0.013530,0.002117,0.102391,1,True,8
4,NeuralNetFastAI,0.864407,0.914894,accuracy,0.017399,0.009332,0.810386,0.017399,0.009332,0.810386,1,True,7
5,WeightedEnsemble_L2,0.864407,0.914894,accuracy,0.019316,0.010027,0.884135,0.001917,0.000696,0.073749,2,True,11
6,ExtraTreesEntr,0.864407,0.872340,accuracy,0.066000,0.075425,0.604418,0.066000,0.075425,0.604418,1,True,6
7,ExtraTreesGini,0.864407,0.872340,accuracy,0.066269,0.075642,0.603105,0.066269,0.075642,0.603105,1,True,5
8,LightGBMXT,0.847458,0.893617,accuracy,0.002789,0.000541,0.269475,0.002789,0.000541,0.269475,1,True,1
9,LightGBMLarge,0.830508,0.872340,accuracy,0.002778,0.000540,0.337854,0.002778,0.000540,0.337854,1,True,10
10,NeuralNetTorch,0.813559,0.893617,accuracy,0.012233,0.006397,0.697268,0.012233,0.006397,0.697268,1,True,9

In [105]:
hhhun_TabPre.leaderboard( silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,XGBoost,0.914894,accuracy,0.002117,0.102391,0.002117,0.102391,1,True,8
1,NeuralNetFastAI,0.914894,accuracy,0.009332,0.810386,0.009332,0.810386,1,True,7
2,WeightedEnsemble_L2,0.914894,accuracy,0.010027,0.884135,0.000696,0.073749,2,True,11
3,LightGBM,0.893617,accuracy,0.000488,0.259475,0.000488,0.259475,1,True,2
4,LightGBMXT,0.893617,accuracy,0.000541,0.269475,0.000541,0.269475,1,True,1
5,NeuralNetTorch,0.893617,accuracy,0.006397,0.697268,0.006397,0.697268,1,True,9
6,LightGBMLarge,0.872340,accuracy,0.000540,0.337854,0.000540,0.337854,1,True,10
7,RandomForestEntr,0.872340,accuracy,0.066584,0.610194,0.066584,0.610194,1,True,4
8,ExtraTreesEntr,0.872340,accuracy,0.075425,0.604418,0.075425,0.604418,1,True,6
9,ExtraTreesGini,0.872340,accuracy,0.075642,0.603105,0.075642,0.603105,1,True,5
10,RandomForestGini,0.851064,accuracy,0.076370,0.604541,0.076370,0.604541,1,True,3

In [106]:
##--original
# #Show the best model
# hhhun_TabPre.get_model_best()
##--modified
hhhun_TabPre.model_best

'WeightedEnsemble_L2'

# COMBINED

## TAKE A PEEK

In [107]:
# load Switzerland datafile
switzerland_csv_path = "processed.switzerland.data"
switzerland_data = pd.read_csv(switzerland_csv_path, header = None)
# assign column names
##--original
# switzerland_data.set_axis(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
#                   'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
#                   'ca', 'thal', 'num'], axis = 1, inplace = True)
##--modified
switzerland_data.columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
                  'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
                  'ca', 'thal', 'num']

In [108]:
# load VA datafile
va_csv_path = "processed.va.data"
va_data = pd.read_csv(va_csv_path, header = None)
# assign column names
##--original
# va_data.set_axis(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
#                   'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
#                   'ca', 'thal', 'num'], axis = 1, inplace = True)
##--modified
va_data.columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
                  'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
                  'ca', 'thal', 'num']

In [109]:
switzerland_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,32,1,1,95,0,?,0,127,0,.7,1,?,?,1
1,34,1,4,115,0,?,?,154,0,.2,1,?,?,1
2,35,1,4,?,0,?,0,130,1,?,?,?,7,3
3,36,1,4,110,0,?,0,125,1,1,2,?,6,1
4,38,0,4,105,0,?,0,166,0,2.8,1,?,?,2

In [110]:
va_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,4,140,260,0,1,112,1,3,2,?,?,2
1,44,1,4,130,209,0,1,127,0,0,?,?,?,0
2,60,1,4,132,218,0,1,140,1,1.5,3,?,?,2
3,55,1,4,142,228,0,1,149,1,2.5,1,?,?,1
4,66,1,3,110,213,1,2,99,1,1.3,2,?,?,0

In [111]:
switzerland_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       123 non-null    int64
 1   sex       123 non-null    int64
 2   cp        123 non-null    int64
 3   trestbps  123 non-null    object
 4   chol      123 non-null    int64
 5   fbs       123 non-null    object
 6   restecg   123 non-null    object
 7   thalach   123 non-null    object
 8   exang     123 non-null    object
 9   oldpeak   123 non-null    object
 10  slope     123 non-null    object
 11  ca        123 non-null    object
 12  thal      123 non-null    object
 13  num       123 non-null    int64
dtypes: int64(5), object(9)
memory usage: 13.6+ KB

In [112]:
va_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       200 non-null    int64
 1   sex       200 non-null    int64
 2   cp        200 non-null    int64
 3   trestbps  200 non-null    object
 4   chol      200 non-null    object
 5   fbs       200 non-null    object
 6   restecg   200 non-null    int64
 7   thalach   200 non-null    object
 8   exang     200 non-null    object
 9   oldpeak   200 non-null    object
 10  slope     200 non-null    object
 11  ca        200 non-null    object
 12  thal      200 non-null    object
 13  num       200 non-null    int64
dtypes: int64(5), object(9)
memory usage: 22.0+ KB

## DATA PREPROCESSING

### COPY DATASETS

In [113]:
switzerland = switzerland_data.copy()
va = va_data.copy()

### MISSING VALUES

#### CONVERT ? TO NAN

In [114]:
##--original
# switzerland = switzerland.replace('?', np.NaN) # replace '?' values with NaN so can impute
##--modified
switzerland = switzerland.replace('?', np.nan) # replace '?' values with NaN so can impute

switzerland[['age', 'trestbps', 'chol', 'thalach', 'oldpeak']].astype(float) # convert dtype
switzerland.tail() # to verify didn't mess up dataframe IDs

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
118,70,1,4,115,0,0,1,92,1,0,2,NaN,7,1
119,70,1,4,140,0,1,0,157,1,2,2,NaN,7,3
120,72,1,3,160,0,NaN,2,114,0,1.6,2,2,NaN,0
121,73,0,3,160,0,0,1,121,0,0,1,NaN,3,1
122,74,1,2,145,0,NaN,1,123,0,1.3,1,NaN,NaN,1

In [115]:
# make dataset version for plotting purposes
switzerland_for_plot = switzerland.copy()

In [116]:
##--original
# va = va.replace('?', np.NaN) # replace '?' values with NaN so can impute
##--modified
va = va.replace('?', np.nan) # replace '?' values with NaN so can impute

va[['age', 'trestbps', 'chol', 'thalach', 'oldpeak']].astype(float) # convert dtype
va.tail() # to verify didn't mess up dataframe IDs

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
195,54,0,4,127,333,1,1,154,0,0,NaN,NaN,NaN,1
196,62,1,1,NaN,139,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
197,55,1,4,122,223,1,1,100,0,0,NaN,NaN,6,2
198,58,1,4,NaN,385,1,2,NaN,NaN,NaN,NaN,NaN,NaN,0
199,62,1,2,120,254,0,2,93,1,0,NaN,NaN,NaN,1

In [117]:
# make dataset version for plotting purposes
va_for_plot = va.copy()

#### DROP IF MISSING >50%

In [118]:
switzerland.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       123 non-null    int64
 1   sex       123 non-null    int64
 2   cp        123 non-null    int64
 3   trestbps  121 non-null    object
 4   chol      123 non-null    int64
 5   fbs       48 non-null     object
 6   restecg   122 non-null    object
 7   thalach   122 non-null    object
 8   exang     122 non-null    object
 9   oldpeak   117 non-null    object
 10  slope     106 non-null    object
 11  ca        5 non-null      object
 12  thal      71 non-null     object
 13  num       123 non-null    int64
dtypes: int64(5), object(9)
memory usage: 13.6+ KB

In [119]:
va.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       200 non-null    int64
 1   sex       200 non-null    int64
 2   cp        200 non-null    int64
 3   trestbps  144 non-null    object
 4   chol      193 non-null    object
 5   fbs       193 non-null    object
 6   restecg   200 non-null    int64
 7   thalach   147 non-null    object
 8   exang     147 non-null    object
 9   oldpeak   144 non-null    object
 10  slope     98 non-null     object
 11  ca        2 non-null      object
 12  thal      34 non-null     object
 13  num       200 non-null    int64
dtypes: int64(5), object(9)
memory usage: 22.0+ KB

In [120]:
# Switzerland - drop fbs, ca, and thal due to >50% of values missing
# VA - drop slope, ca, and thal due to >50% of values missing
# as combined dataset - drop fbs, slope, ca, and thal
switzerland_mod = switzerland.copy()
switzerland_mod.drop(['fbs', 'slope', 'ca', 'thal'], axis=1, inplace=True)
va_mod = va.copy()
va_mod.drop(['fbs', 'slope', 'ca', 'thal'], axis=1, inplace=True)

#### IMPUTE TO MODE OR MEAN

##### SWITZERLAND

In [121]:
switzerland_mod.info()
# to impute -
#    to mode: restecg, exang
#    to mean: trestbps, thalach, oldpeak

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       123 non-null    int64
 1   sex       123 non-null    int64
 2   cp        123 non-null    int64
 3   trestbps  121 non-null    object
 4   chol      123 non-null    int64
 5   restecg   122 non-null    object
 6   thalach   122 non-null    object
 7   exang     122 non-null    object
 8   oldpeak   117 non-null    object
 9   num       123 non-null    int64
dtypes: int64(5), object(5)
memory usage: 9.7+ KB

In [122]:
# impute discrete values using mode ()
imputeMode = SimpleImputer(strategy="most_frequent") # create mode imputer
switzerland_mod_disc = pd.concat([switzerland_mod.pop(x) for x in ['restecg', 'exang']], axis=1) # isolate discrete
imputeMode.fit(switzerland_mod_disc) # fit - learns the data
imputed_disc = imputeMode.transform(switzerland_mod_disc) # transform - imputes with chosen strategy
switzerland_mod_disc_imp = pd.DataFrame(imputed_disc, columns=switzerland_mod_disc.columns, index=switzerland_mod.index) # back to pandas DataFrame
switzerland_mod_disc_imp.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   restecg  123 non-null    object
 1   exang    123 non-null    object
dtypes: object(2)
memory usage: 2.1+ KB

In [123]:
# impute continuous values using mean
imputeMean = SimpleImputer(strategy="mean") # create mode imputer
switzerland_mod_cont = pd.concat([switzerland_mod.pop(x) for x in ['trestbps', 'oldpeak', 'thalach']], axis=1) # isolate continuous
imputeMean.fit(switzerland_mod_cont) # fit - learns the data
imputed_cont = imputeMean.transform(switzerland_mod_cont) # transform - imputes with chosen strategy
switzerland_mod_cont_imp = pd.DataFrame(imputed_cont, columns=switzerland_mod_cont.columns, index=switzerland_mod.index) # back to pandas DataFrame
switzerland_mod_cont_imp.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   trestbps  123 non-null    float64
 1   oldpeak   123 non-null    float64
 2   thalach   123 non-null    float64
dtypes: float64(3)
memory usage: 3.0 KB

In [124]:
# Combine cat, cont, and remaining
switzerland_mod_imp = pd.concat((switzerland_mod_cont_imp, switzerland_mod_disc_imp, switzerland_mod), axis=1)

In [125]:
switzerland_mod_imp.head() # check for anything obviously wonky

     trestbps   oldpeak  thalach restecg exang  age  sex  cp  chol  num
0   95.000000  0.700000    127.0       0     0   32    1   1     0    1
1  115.000000  0.200000    154.0       0     0   34    1   4     0    1
2  130.206612  0.653846    130.0       0     1   35    1   4     0    3
3  110.000000  1.000000    125.0       0     1   36    1   4     0    1
4  105.000000  2.800000    166.0       0     0   38    0   4     0    2

In [126]:
switzerland_mod_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   trestbps  123 non-null    float64
 1   oldpeak   123 non-null    float64
 2   thalach   123 non-null    float64
 3   restecg   123 non-null    object
 4   exang     123 non-null    object
 5   age       123 non-null    int64
 6   sex       123 non-null    int64
 7   cp        123 non-null    int64
 8   chol      123 non-null    int64
 9   num       123 non-null    int64
dtypes: float64(3), int64(5), object(2)
memory usage: 9.7+ KB

##### VA

In [127]:
 va_mod.info()
# to impute -
#    to mode: exang
#    to mean: trestbps, thalach, oldpeak, chol

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       200 non-null    int64
 1   sex       200 non-null    int64
 2   cp        200 non-null    int64
 3   trestbps  144 non-null    object
 4   chol      193 non-null    object
 5   restecg   200 non-null    int64
 6   thalach   147 non-null    object
 7   exang     147 non-null    object
 8   oldpeak   144 non-null    object
 9   num       200 non-null    int64
dtypes: int64(5), object(5)
memory usage: 15.8+ KB

In [128]:
# impute discrete values using mode ()
imputeMode = SimpleImputer(strategy="most_frequent") # create mode imputer
va_mod_disc = pd.concat([va_mod.pop(x) for x in ['exang']], axis=1) # isolate discrete
imputeMode.fit(va_mod_disc) # fit - learns the data
imputed_disc = imputeMode.transform(va_mod_disc) # transform - imputes with chosen strategy
va_mod_disc_imp = pd.DataFrame(imputed_disc, columns=va_mod_disc.columns, index=va_mod.index) # back to pandas DataFrame
va_mod_disc_imp.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   exang   200 non-null    object
dtypes: object(1)
memory usage: 1.7+ KB

In [129]:
# impute continuous values using mean
imputeMean = SimpleImputer(strategy="mean") # create mode imputer
va_mod_cont = pd.concat([va_mod.pop(x) for x in ['trestbps', 'chol', 'oldpeak', 'thalach']], axis=1) # isolate continuous
imputeMean.fit(va_mod_cont) # fit - learns the data
imputed_cont = imputeMean.transform(va_mod_cont) # transform - imputes with chosen strategy
va_mod_cont_imp = pd.DataFrame(imputed_cont, columns=va_mod_cont.columns, index=va_mod.index) # back to pandas DataFrame
va_mod_cont_imp.info() # check for missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   trestbps  200 non-null    float64
 1   chol      200 non-null    float64
 2   oldpeak   200 non-null    float64
 3   thalach   200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [130]:
# Combine cat, cont, and remaining
va_mod_imp = pd.concat((va_mod_cont_imp, va_mod_disc_imp, va_mod), axis=1)

In [131]:
va_mod_imp.head() # check for anything obviously wonky

   trestbps   chol  oldpeak  thalach exang  age  sex  cp  restecg  num
0     140.0  260.0      3.0    112.0     1   63    1   4        1    2
1     130.0  209.0      0.0    127.0     0   44    1   4        1    0
2     132.0  218.0      1.5    140.0     1   60    1   4        1    2
3     142.0  228.0      2.5    149.0     1   55    1   4        1    1
4     110.0  213.0      1.3     99.0     1   66    1   3        2    0

In [132]:
va_mod_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   trestbps  200 non-null    float64
 1   chol      200 non-null    float64
 2   oldpeak   200 non-null    float64
 3   thalach   200 non-null    float64
 4   exang     200 non-null    object
 5   age       200 non-null    int64
 6   sex       200 non-null    int64
 7   cp        200 non-null    int64
 8   restecg   200 non-null    int64
 9   num       200 non-null    int64
dtypes: float64(4), int64(5), object(1)
memory usage: 15.8+ KB

### BINARY LABEL

In [133]:
##--original
# switzerland_mod_imp['num'][switzerland_mod_imp['num'] > 0] = 1
# switzerland_mod_imp.value_counts('num')
##--modified
switzerland_mod_imp.loc[switzerland_mod_imp["num"] > 0, "num"] = 1
switzerland_mod_imp.value_counts("num")

num
1    115
0      8
Name: count, dtype: int64

In [135]:
##--original
# va_mod_imp['num'][va_mod_imp['num'] > 0] = 1
# va_mod_imp.value_counts('num')
##--modified
va_mod_imp.loc[va_mod_imp["num"] > 0, "num"] = 1
va_mod_imp.value_counts("num")

num
1    149
0     51
Name: count, dtype: int64

### CREATE COMBINED DATASET

In [136]:
#cleveland.info()
# for combined, drop - slope, ca, thal, fbs

In [137]:
cleveland_comb = cleveland.copy()

In [138]:
cleveland_comb.drop(['fbs', 'slope', 'ca', 'thal'], axis=1, inplace=True)
#cleveland_comb.info()

In [139]:
#hungarian_imp.info()
# for combined, drop - fbs

In [140]:
hungarian_comb = hungarian_imp.copy()

In [141]:
hungarian_comb.drop(['fbs'], axis=1, inplace=True)
#hungarian_comb.info()

In [142]:
#switzerland_mod_imp.info()

In [143]:
#va_mod_imp.info()

In [144]:
combined = pd.concat((cleveland_comb, hungarian_comb, switzerland_mod_imp, va_mod_imp), axis=0, ignore_index=True)
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       920 non-null    float64
 1   sex       920 non-null    float64
 2   cp        920 non-null    float64
 3   trestbps  920 non-null    float64
 4   chol      920 non-null    float64
 5   restecg   920 non-null    object
 6   thalach   920 non-null    float64
 7   exang     920 non-null    object
 8   oldpeak   920 non-null    float64
 9   num       920 non-null    float64
dtypes: float64(8), object(2)
memory usage: 72.0+ KB

### STRATIFIED SAMPLING

In [145]:
combined_strat = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in combined_strat.split(combined, combined["num"]):
  combined_strat_train = combined.loc[train_index]
  combined_strat_test = combined.loc[test_index]

In [146]:
combined_strat_test["num"].value_counts()/len(combined_strat_test)

num
1.0    0.554348
0.0    0.445652
Name: count, dtype: float64

In [147]:
combined_strat_train["num"].value_counts()/len(combined_strat_train)

num
1.0    0.552989
0.0    0.447011
Name: count, dtype: float64

In [148]:
# split stratified data
combined_strat_train_X = combined_strat_train.drop([heart_label], axis=1)
combined_strat_train_y = combined_strat_train[heart_label]
combined_strat_test_X = combined_strat_test.drop([heart_label], axis=1)
combined_strat_test_y = combined_strat_test[heart_label]
combined_strat_train_X.sample(5)

      age  sex   cp    trestbps   chol restecg     thalach exang   oldpeak
731  59.0  1.0  4.0  140.000000    0.0       1  117.000000     1  1.000000
383  55.0  1.0  3.0  110.000000  277.0     0.0  160.000000   0.0  0.000000
708  66.0  0.0  4.0  155.000000    0.0       0   90.000000     0  0.000000
392  55.0  1.0  4.0  140.000000  229.0     0.0  110.000000   1.0  0.500000
758  58.0  1.0  4.0  133.763889  203.0       0  122.795918     1  1.320833

## BINARY MODEL

In [149]:
# Create an instance and then fit the train data
comb_TabPre = TabularPredictor(label=heart_label, path='.').fit(combined_strat_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.70 GB / 12.67 GB (68.6%)
Disk Space Avail:   66.60 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    736
Train Data Columns: 9
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8901.70 MB
	Train Data (Original)  Memory Usage: 0.09 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 7 | ['age', 'sex', 'cp', 'trestbps', 'chol', ...]
		('object', []) : 2 | ['restecg', 'exang']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['restecg', 'exang']
		('float', [])     : 6 | ['age', 'cp', 'trestbps', 'chol', 'thalach', ...]
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	9 features in original data used to generate 9 features in processed data.
	Train Data (Processed) Memory Usage: 0.04 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 588, Val Rows: 148
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8041	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.7 GB
	0.8041	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.7635	 = Validation score   (accuracy)
	1.1s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.7905	 = Validation score   (accuracy)
	1.31s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.7838	 = Validation score   (accuracy)
	1.16s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.777	 = Validation score   (accuracy)
	1.92s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.6 GB
No improvement since epoch 8: early stopping
	0.7905	 = Validation score   (accuracy)
	2.04s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.8108	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.6 GB
	0.8041	 = Validation score   (accuracy)
	2.99s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.5 GB
	0.7703	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.5 GB
	Ensemble Weights: {'XGBoost': 1.0}
	0.8108	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.46s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 16206.9 rows/s (148 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (148 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [150]:
comb_pred = comb_TabPre.predict(combined_strat_test_X)
comb_perf = comb_TabPre.evaluate_predictions(y_true=combined_strat_test_y, y_pred=comb_pred, auxiliary_metrics=True)

In [151]:
comb_perf2 =  comb_TabPre.evaluate(data=combined_strat_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [152]:
comb_perf3 =  comb_TabPre.evaluate(data=combined_strat_test, auxiliary_metrics=True, model='RandomForestEntr')

In [153]:
comb_perf4 =  comb_TabPre.evaluate(data=combined_strat_test, auxiliary_metrics=True, model='ExtraTreesGini')

In [154]:
#Show the leaderboard
comb_TabPre.leaderboard(combined_strat_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBM,0.853261,0.804054,accuracy,0.007650,0.004116,0.679055,0.007650,0.004116,0.679055,1,True,2
1,XGBoost,0.847826,0.810811,accuracy,0.012237,0.008379,0.489705,0.012237,0.008379,0.489705,1,True,8
2,WeightedEnsemble_L2,0.847826,0.810811,accuracy,0.013578,0.009132,0.556053,0.001342,0.000753,0.066347,2,True,11
3,RandomForestEntr,0.847826,0.790541,accuracy,0.097120,0.114746,1.311252,0.097120,0.114746,1.311252,1,True,4
4,ExtraTreesEntr,0.836957,0.777027,accuracy,0.100730,0.145623,1.917050,0.100730,0.145623,1.917050,1,True,6
5,RandomForestGini,0.836957,0.763514,accuracy,0.101225,0.077340,1.104393,0.101225,0.077340,1.104393,1,True,3
6,ExtraTreesGini,0.826087,0.783784,accuracy,0.102030,0.086559,1.162360,0.102030,0.086559,1.162360,1,True,5
7,NeuralNetTorch,0.820652,0.804054,accuracy,0.011064,0.008574,2.994973,0.011064,0.008574,2.994973,1,True,9
8,LightGBMXT,0.815217,0.804054,accuracy,0.005265,0.010128,0.554835,0.005265,0.010128,0.554835,1,True,1
9,NeuralNetFastAI,0.815217,0.790541,accuracy,0.013906,0.026142,2.036667,0.013906,0.026142,2.036667,1,True,7
10,LightGBMLarge,0.788043,0.770270,accuracy,0.003583,0.002256,0.521266,0.003583,0.002256,0.521266,1,True,10

In [155]:
#Show the leaderboard
comb_TabPre.leaderboard( silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,XGBoost,0.810811,accuracy,0.008379,0.489705,0.008379,0.489705,1,True,8
1,WeightedEnsemble_L2,0.810811,accuracy,0.009132,0.556053,0.000753,0.066347,2,True,11
2,LightGBM,0.804054,accuracy,0.004116,0.679055,0.004116,0.679055,1,True,2
3,NeuralNetTorch,0.804054,accuracy,0.008574,2.994973,0.008574,2.994973,1,True,9
4,LightGBMXT,0.804054,accuracy,0.010128,0.554835,0.010128,0.554835,1,True,1
5,NeuralNetFastAI,0.790541,accuracy,0.026142,2.036667,0.026142,2.036667,1,True,7
6,RandomForestEntr,0.790541,accuracy,0.114746,1.311252,0.114746,1.311252,1,True,4
7,ExtraTreesGini,0.783784,accuracy,0.086559,1.162360,0.086559,1.162360,1,True,5
8,ExtraTreesEntr,0.777027,accuracy,0.145623,1.917050,0.145623,1.917050,1,True,6
9,LightGBMLarge,0.770270,accuracy,0.002256,0.521266,0.002256,0.521266,1,True,10
10,RandomForestGini,0.763514,accuracy,0.077340,1.104393,0.077340,1.104393,1,True,3

In [157]:
##--original
# #Show the best model
# comb_TabPre.get_model_best()
##--modified
comb_TabPre.model_best

'WeightedEnsemble_L2'

## CORRELATED

### ADDITIONAL DATA PREPROCESSING
(starting after combined dataset created and before stratified sampling above)

In [158]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       920 non-null    float64
 1   sex       920 non-null    float64
 2   cp        920 non-null    float64
 3   trestbps  920 non-null    float64
 4   chol      920 non-null    float64
 5   restecg   920 non-null    object
 6   thalach   920 non-null    float64
 7   exang     920 non-null    object
 8   oldpeak   920 non-null    float64
 9   num       920 non-null    float64
dtypes: float64(8), object(2)
memory usage: 72.0+ KB

In [159]:
# check correlation
combined_correlation = combined.corr()
combined_correlation['num'].sort_values()
# only trestbps has abs(corr) < 0.2

thalach    -0.385972
chol       -0.234679
restecg     0.062304
trestbps    0.103828
age         0.282700
sex         0.307284
oldpeak     0.373382
exang       0.443433
cp          0.471712
num         1.000000
Name: num, dtype: float64

In [160]:
# eliminate columns with correlation less than abs(0.2)
drop_columns = ['trestbps']
combined_downsized = combined.drop(columns = drop_columns)
combined_downsized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age      920 non-null    float64
 1   sex      920 non-null    float64
 2   cp       920 non-null    float64
 3   chol     920 non-null    float64
 4   restecg  920 non-null    object
 5   thalach  920 non-null    float64
 6   exang    920 non-null    object
 7   oldpeak  920 non-null    float64
 8   num      920 non-null    float64
dtypes: float64(7), object(2)
memory usage: 64.8+ KB

In [161]:
combined_downsized_strat = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in combined_downsized_strat.split(combined_downsized, combined["num"]):
  combined_downsized_strat_train = combined_downsized.loc[train_index]
  combined_downsized_strat_test = combined_downsized.loc[test_index]

In [162]:
combined_downsized_strat_test["num"].value_counts()/len(combined_downsized_strat_test)

num
1.0    0.554348
0.0    0.445652
Name: count, dtype: float64

In [163]:
combined_downsized_strat_train["num"].value_counts()/len(combined_downsized_strat_train)

num
1.0    0.552989
0.0    0.447011
Name: count, dtype: float64

In [164]:
# split stratified data
combined_downsized_strat_train_X = combined_downsized_strat_train.drop([heart_label], axis=1)
combined_downsized_strat_train_y = combined_downsized_strat_train[heart_label]
combined_downsized_strat_test_X = combined_downsized_strat_test.drop([heart_label], axis=1)
combined_downsized_strat_test_y = combined_downsized_strat_test[heart_label]
combined_downsized_strat_train_X.sample(5)

      age  sex   cp   chol restecg  thalach exang  oldpeak
132  29.0  1.0  2.0  204.0     2.0    202.0   0.0      0.0
311  37.0  1.0  4.0  207.0     0.0    130.0   1.0      1.5
281  47.0  1.0  3.0  253.0     0.0    179.0   0.0      0.0
223  53.0  1.0  4.0  282.0     0.0     95.0   1.0      2.0
400  39.0  1.0  3.0  147.0     0.0    160.0   0.0      0.0

### BINARY MODEL - correlated

In [165]:
# Create an instance and then fit the train data
comb_downsized_TabPre = TabularPredictor(label=heart_label, path='.').fit(combined_downsized_strat_train)

Warning: path already exists! This predictor may overwrite an existing predictor! path="."
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.6.0+cu124
CUDA Version:       12.4
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       8.53 GB / 12.67 GB (67.3%)
Disk Space Avail:   66.58 GB / 118.86 GB (56.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/content"
Train Data Rows:    736
Train Data Columns: 8
Label Column:       num
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(1.0), np.float64(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8734.04 MB
	Train Data (Original)  Memory Usage: 0.09 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['age', 'sex', 'cp', 'chol', 'thalach', ...]
		('object', []) : 2 | ['restecg', 'exang']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['restecg', 'exang']
		('float', [])     : 5 | ['age', 'cp', 'chol', 'thalach', 'oldpeak']
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	8 features in original data used to generate 8 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 588, Val Rows: 148
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.5 GB
	0.7905	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.5 GB
	0.7973	 = Validation score   (accuracy)
	0.88s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=2, gpus=0
	0.7905	 = Validation score   (accuracy)
	1.38s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=2, gpus=0
	0.8041	 = Validation score   (accuracy)
	1.17s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesGini ...
	Fitting with cpus=2, gpus=0
	0.7905	 = Validation score   (accuracy)
	0.88s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=2, gpus=0
	0.777	 = Validation score   (accuracy)
	0.92s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.5 GB
	0.7973	 = Validation score   (accuracy)
	1.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	0.7905	 = Validation score   (accuracy)
	0.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.0/8.5 GB
	0.8041	 = Validation score   (accuracy)
	2.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.1/8.5 GB
	0.75	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/8.5 GB
	Ensemble Weights: {'RandomForestEntr': 0.8, 'ExtraTreesGini': 0.2}
	0.8108	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 11.17s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 864.0 rows/s (148 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (148 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content")

In [166]:
comb_downsized_pred = comb_downsized_TabPre.predict(combined_downsized_strat_test_X)
comb_downsized_perf = comb_downsized_TabPre.evaluate_predictions(
    y_true=combined_downsized_strat_test_y, y_pred=comb_downsized_pred, auxiliary_metrics=True)

In [167]:
comb_downsized_perf2 =  comb_downsized_TabPre.evaluate(data=combined_downsized_strat_test, auxiliary_metrics=True, model='WeightedEnsemble_L2')

In [168]:
comb_downsized_perf3 =  comb_downsized_TabPre.evaluate(data=combined_downsized_strat_test, auxiliary_metrics=True, model='RandomForestEntr')

In [169]:
comb_downsized_perf4 =  comb_downsized_TabPre.evaluate(data=combined_downsized_strat_test, auxiliary_metrics=True, model='RandomForestGini')

In [170]:
#Show the leaderboard
comb_downsized_TabPre.leaderboard(combined_downsized_strat_test, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForestEntr,0.842391,0.804054,accuracy,0.087357,0.090269,1.170863,0.087357,0.090269,1.170863,1,True,4
1,WeightedEnsemble_L2,0.842391,0.810811,accuracy,0.181020,0.171288,2.113114,0.001457,0.000744,0.063994,2,True,11
2,NeuralNetTorch,0.836957,0.804054,accuracy,0.010150,0.007990,2.148582,0.010150,0.007990,2.148582,1,True,9
3,XGBoost,0.836957,0.790541,accuracy,0.011558,0.008319,0.341329,0.011558,0.008319,0.341329,1,True,8
4,RandomForestGini,0.836957,0.790541,accuracy,0.097562,0.082567,1.378913,0.097562,0.082567,1.378913,1,True,3
5,ExtraTreesEntr,0.836957,0.777027,accuracy,0.101368,0.078933,0.921271,0.101368,0.078933,0.921271,1,True,6
6,LightGBM,0.831522,0.797297,accuracy,0.005412,0.004247,0.876873,0.005412,0.004247,0.876873,1,True,2
7,ExtraTreesGini,0.831522,0.790541,accuracy,0.092206,0.080276,0.878257,0.092206,0.080276,0.878257,1,True,5
8,LightGBMXT,0.826087,0.790541,accuracy,0.004412,0.003525,0.598257,0.004412,0.003525,0.598257,1,True,1
9,NeuralNetFastAI,0.815217,0.797297,accuracy,0.013200,0.014362,1.035067,0.013200,0.014362,1.035067,1,True,7
10,LightGBMLarge,0.793478,0.750000,accuracy,0.004686,0.002484,0.514148,0.004686,0.002484,0.514148,1,True,10

In [171]:
comb_downsized_TabPre.leaderboard(silent=True)

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.810811,accuracy,0.171288,2.113114,0.000744,0.063994,2,True,11
1,NeuralNetTorch,0.804054,accuracy,0.007990,2.148582,0.007990,2.148582,1,True,9
2,RandomForestEntr,0.804054,accuracy,0.090269,1.170863,0.090269,1.170863,1,True,4
3,LightGBM,0.797297,accuracy,0.004247,0.876873,0.004247,0.876873,1,True,2
4,NeuralNetFastAI,0.797297,accuracy,0.014362,1.035067,0.014362,1.035067,1,True,7
5,LightGBMXT,0.790541,accuracy,0.003525,0.598257,0.003525,0.598257,1,True,1
6,XGBoost,0.790541,accuracy,0.008319,0.341329,0.008319,0.341329,1,True,8
7,ExtraTreesGini,0.790541,accuracy,0.080276,0.878257,0.080276,0.878257,1,True,5
8,RandomForestGini,0.790541,accuracy,0.082567,1.378913,0.082567,1.378913,1,True,3
9,ExtraTreesEntr,0.777027,accuracy,0.078933,0.921271,0.078933,0.921271,1,True,6
10,LightGBMLarge,0.750000,accuracy,0.002484,0.514148,0.002484,0.514148,1,True,10

In [173]:
##--original
# #Show the best model
# comb_downsized_TabPre.get_model_best()
##--modified
comb_downsized_TabPre.model_best

'WeightedEnsemble_L2'